### ISSUE TITLE
Local deploy following README didn't succeed

### ISSUE THREAD

**Issue by Bachibouzouk** [susiai/susi_chat#1]
Hello, I came across susi_chat watching https://media.ccc.de/v/clt24-186-wie-funktioniert-chatgpt-gibt-es-das-auch-als-open-source and I would like to try it out locally.

I am a total beginner in this and I cloned both your repository and the current version of llama.cpp, then from your repository I ran
``` 
../llama.cpp/server --host 0.0.0.0 --port 8001 -ngl 0 --path ../susi_chat/chat_terminal/ -m ~/models/openchat_3.5.Q2_K.gguf
``` 
but it failed because bash tells me `../llama.cpp/server` doesn't exists. Did you run some specific commands to install llama.cpp? I looked on their readme but I find it very chaotic. As your readme's last update is 4 month old I guess it means it worked with the llama.ccp version from then?

Thank you in advance! 

PS1: I am using 20.04.1-Ubuntu
PS2: maybe I am too beginner and I am not worth your time, I could understand that ^^

**Comment by Orbiter** [comment]
yes, I was using the llama.cpp project to run the LLM server. You must clone and build the project to a path parallel to the susi_chat path. This is easy: consider you are in the susi_chat path, then:

```
cd ..
git clone https://github.com/ggerganov/llama.cpp.git
cd llama.cpp
make
```

This will clone and build the llama.cpp project and the command above in your question should work.

**Comment by Bachibouzouk** [comment]
It did work, thank you for your help :)
